apiVersion: v1
kind: Service
metadata:
  name: go-kubernetes-demo
  namespace: demo
spec:
  selector:
    app: go-kubernetes-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
